### ISSUE TITLE
Ontology can't be uploaded with ModelUploader

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/opendigitaltwins-energygrid#51]
Just tried to upload the complete ontology with [Model Uploader](https://github.com/Azure/opendigitaltwins-tools/tree/master/ModelUploader). Unfortunately the '.vscode' subfolder in the 'Ontology' folder, and its *.json files inside, will cause a crash of the ModelUploader. 

This can be fixed by removing the '.vscode' subfolder in the 'Ontology' folder or by fixing the ModelUploader tool. I'll work on a PR for that.

**Comment by op-ravi** [comment]
Thank you, Jürgen. I validated it via ADT explorer https://explorer.digitaltwins.azure.net. I can remove the .vscode folder now.

**Comment by op-ravi** [comment]
I removed it, so please try when you can and let me know if it works with the Model uploader. Thanks again!

**Comment by JMayrbaeurl** [comment]
Still doesn't work, because of schema issues. PR #57 will fix this

**Comment by JMayrbaeurl** [comment]
@op-ravi Works now
