### ISSUE TITLE
Ontology contains multiple model files for 'dtmi:digitaltwins:ngsi_ld:cim:energy:GeneratingUnit;1'

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/opendigitaltwins-energygrid#52]
Just tried to upload the ontology with [Model Uploader](https://github.com/Azure/opendigitaltwins-tools/tree/master/ModelUploader). ModelUploader has detected two model files that both define the same model interface 'dtmi:digitaltwins:ngsi_ld:cim:energy:GeneratingUnit;1'

First at location: Generation/GeneratingUnit.json
Second at location: Prosumers/Distributed Energy Resource/GeneratingUnit/GeneratingUnit.json

One of them should be removed.

**Comment by op-ravi** [comment]
I was thinking about this and fixed it soon.

**Comment by op-ravi** [comment]
Fixed, I removed the duplicate entities.
